server:
  port: 9091

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaulZone: http://localhost:8761/eureka
spring:
  application:
    name: HOTEL-SERVICE         
