server:
  port: 9093
spring:
  application:
    name: SOAP-SERVICE
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaulZone: http://localhost:8761/eureka
